CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AnimeCaches" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TitleRomaji" text NOT NULL,
    "TitleEnglish" text,
    "TitleNative" text,
    "Description" text NOT NULL,
    "CoverImage" text,
    "BannerImage" text,
    "Episodes" integer,
    "CurrentEpisodes" integer,
    "Status" text NOT NULL,
    "Format" text,
    "CountryOfOrigin" text,
    "Is3D" boolean NOT NULL,
    "Genres" text[] NOT NULL,
    "AverageScore" integer,
    "SeasonYear" integer,
    "StartDate" text,
    "TrailerSite" text,
    "TrailerId" text,
    "ViewCount" integer NOT NULL,
    "LastSyncedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AnimeCaches" PRIMARY KEY ("Id")
);

CREATE TABLE "Badges" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "IconUrl" text NOT NULL,
    "RequiredPoints" integer NOT NULL,
    "Description" text NOT NULL,
    CONSTRAINT "PK_Badges" PRIMARY KEY ("Id")
);

CREATE TABLE "Borders" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "FrameUrl" text NOT NULL,
    "RequiredPoints" integer NOT NULL,
    "Description" text NOT NULL,
    CONSTRAINT "PK_Borders" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "Username" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "AvatarUrl" text,
    "Role" text NOT NULL,
    "Points" integer NOT NULL,
    "CurrentBadgeId" uuid,
    "CurrentBorderId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Comments" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "AnimeId" integer NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Ratings" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "AnimeId" integer NOT NULL,
    "Score" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Ratings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Ratings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RefreshTokens" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Token" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserInventories" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ItemType" integer NOT NULL,
    "ItemId" uuid NOT NULL,
    "PurchasedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserInventories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserInventories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WatchHistories" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "AnimeId" integer NOT NULL,
    "EpisodeNumber" integer NOT NULL,
    "WatchedProgressSeconds" integer NOT NULL,
    "TotalDurationSeconds" integer NOT NULL,
    "PointAwarded" boolean NOT NULL,
    "LastWatchedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WatchHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WatchHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Comments_UserId" ON "Comments" ("UserId");

CREATE INDEX "IX_Ratings_UserId" ON "Ratings" ("UserId");

CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

CREATE INDEX "IX_UserInventories_UserId" ON "UserInventories" ("UserId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");

CREATE INDEX "IX_WatchHistories_UserId" ON "WatchHistories" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260903093652_InitialCreate', '9.0.2');

CREATE TABLE IF NOT EXISTS "Episodes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AnimeId" integer NOT NULL,
    "EpisodeNumber" integer NOT NULL,
    "Title" text NOT NULL,
    "EmbedUrl" text,
    "HlsUrl" text,
    "ServerName" text NOT NULL,
    "SubtitlesJson" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Episodes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Episodes_AnimeCaches_AnimeId" FOREIGN KEY ("AnimeId") REFERENCES "AnimeCaches" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Episodes_AnimeId_EpisodeNumber" ON "Episodes" ("AnimeId", "EpisodeNumber");

ALTER TABLE "AnimeCaches" ADD COLUMN IF NOT EXISTS "CurrentEpisodes" integer;
ALTER TABLE "AnimeCaches" ADD COLUMN IF NOT EXISTS "EndDate" text;
ALTER TABLE "AnimeCaches" ADD COLUMN IF NOT EXISTS "LastAiredAt" timestamp with time zone;

